//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuffinShopWPF.Model
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class muffins
    {
        public int muffin_id { get; set; }
        public string muffin_name { get; set; }
        public int muffin_price { get; set; }
    }
}
